{% set name = "gammapy" %}
{% set version = "0.20.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 804eab4b475eaa51c4149dc17deb2e53fc5a285968c06d092bc2c304c8f1ea79

build:
  number: 1
  entry_points:
    - gammapy = gammapy.scripts.main:cli
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [py<=37]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - setuptools_scm >=6.2
    - pip !=22.1
    - cython
    - numpy
  run:
    - python
    - setuptools
    - {{ pin_compatible("numpy") }}
    - scipy >=1.4
    - astropy >=5.0
    - regions >=0.5
    - click >=7.0
    - pyyaml >=5.1
    - pydantic >=1.4
    - iminuit >=2.8.0
    - matplotlib >=3.4

test:
  imports:
    - gammapy
    - gammapy.analysis
    - gammapy.astro
    - gammapy.astro.darkmatter
    - gammapy.astro.population
    - gammapy.astro.source
    - gammapy.catalog
    - gammapy.data
    - gammapy.irf
    - gammapy.maps
    - gammapy.modeling
    - gammapy.modeling.models
    - gammapy.scripts
    - gammapy.stats
    - gammapy.utils
    - gammapy.utils.coordinates
    - gammapy.utils.random
  commands:
    - gammapy --help

about:
  home: https://gammapy.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: A Python package for gamma-ray astronomy
  description: |
    Gammapy is an open-source Python package for gamma-ray astronomy built on Numpy and Astropy.
    It is a prototype for the Cherenkov Telescope Array (CTA) science tools,
    and can also be used to analyse data from existing gamma-ray telescopes.
  doc_url: https://docs.gammapy.org/
  dev_url: https://github.com/gammapy/gammapy

extra:
  recipe-maintainers:
    - mwcraig
    - bsipocz
    - adonath
    - registerrier
