appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: Yb0BjCeSo7YAhKZV4/mtk3m2wO2wa4yQE/JD1mu4znKJYoQinBa5/ng3nk9HC3ro/z3/PK9Me8Pfvg+RgRvkR3/+gLfEj8vGrYa/kEoQ+JxUd4HyZZrIb80ji64HS6whgM6EBHJ5HgAcRuCotV/S5tGbRkLPL49Ax7CkUdXmB4atkfVfj/aiUvM417lGWvf34PqKfcFqS4sj8S4Iyf4MYGkLyjM7ttCkvkjoIQM1cvLTPHSpzi22k9kDrYJVI+B6IrSL9MsbqsWA+FltjcrNqIS+JoUKSQr0XFIr6O0lZpqj48Ub215PPTjTQQDZsN2iIMxNS0BWKjgQalJO48OWGYmK8IPMQimZZszybBQ5r394i7UtbKZYPsYSQ9xfI3ZvYwFUtYkQVm2dwgvl4kaDKgfDbq+OO2/yqm7fylXAP8vMsxyjuEJD4j/rS70ZUD4HPR27tKQ/oghzoxMiAqTBPrfKU4+Ix3/NsYRpsrA9nY6rilgA6JjJ0iEdow+nwarbkUUrHebinLhJHA2PUG3vJalnQ93qQA7v3W3ckLQF2lw78HBjPVCYXBxEnI2pRvzGqhVuQypar+ILanGhoZk/FPXfm/wNnZOBxubqvoUaq9DRbxsKwUz9FsGHIVuwEKH6zMoqmVYZ4UMJmnY+8GH9LezjRf+q8O7i4dFwfSKMJxo=}
provider:
  win: azure
